name: Release packages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build_matlab:
    uses: ./.github/workflows/matlab.yaml

  release:
    name: Release new packages
    runs-on: ubuntu-latest
    needs: [build_matlab]

    steps:
      - name: Collect packages
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy final packages to release
        run: |
          mkdir release
          mv artifacts/igraph-SE2-toolbox-${{ github.sha }}/* release

      - name: Upload assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
